name: Implement terraform

on:
  workflow_call:
    secrets:
      awsAccessKeyId:
        required: true
      awsSecretAccessKey:
        required: true

jobs:
  deployWithTerraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init
        
      - name: Terraform Apply
        working-directory: ./terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.awsAccessKeyId }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.awsSecretAccessKey }}
        run: terraform plan